from django.db import models


# Create your models here.

class BigTable(models.Model):
    srch_id = models.IntegerField()
    date_time = models.DateTimeField()
    site_id = models.IntegerField()
    visitor_location_country_id = models.IntegerField(blank=True, null=True)
    visitor_hist_starrating = models.FloatField(blank=True, null=True)
    visitor_hist_adr_usd = models.FloatField(blank=True, null=True)
    prop_country_id = models.IntegerField()
    prop_id = models.IntegerField()
    prop_starrating = models.IntegerField()
    prop_review_score = models.FloatField(blank=True, null=True)
    prop_brand_bool = models.BooleanField()
    prop_location_score1 = models.FloatField(blank=True, null=True)
    prop_location_score2 = models.FloatField(blank=True, null=True)
    prop_log_historical_price = models.FloatField(blank=True, null=True)
    position = models.IntegerField()
    price_usd = models.FloatField(blank=True, null=True)
    promotion_flag = models.BooleanField()
    srch_destination_id = models.IntegerField()
    srch_length_of_stay = models.IntegerField()
    srch_booking_window = models.IntegerField()
    srch_adults_count = models.IntegerField()
    srch_children_count = models.IntegerField()
    srch_room_count = models.IntegerField()
    srch_saturday_night_bool = models.BooleanField()
    srch_query_affinity_score = models.FloatField(blank=True, null=True)
    orig_destination_distance = models.FloatField(blank=True, null=True)
    random_bool = models.BooleanField()
    comp1_rate = models.IntegerField(blank=True, null=True)
    comp1_inv = models.IntegerField(blank=True, null=True)
    comp1_rate_percent_diff = models.FloatField(blank=True, null=True)
    comp2_rate = models.IntegerField(blank=True, null=True)
    comp2_inv = models.IntegerField(blank=True, null=True)
    comp2_rate_percent_diff = models.FloatField(blank=True, null=True)
    comp3_rate = models.IntegerField(blank=True, null=True)
    comp3_inv = models.IntegerField(blank=True, null=True)
    comp3_rate_percent_diff = models.FloatField(blank=True, null=True)
    comp4_rate = models.IntegerField(blank=True, null=True)
    comp4_inv = models.IntegerField(blank=True, null=True)
    comp4_rate_percent_diff = models.FloatField(blank=True, null=True)
    comp5_rate = models.IntegerField(blank=True, null=True)
    comp5_inv = models.IntegerField(blank=True, null=True)
    comp5_rate_percent_diff = models.FloatField(blank=True, null=True)
    comp6_rate = models.IntegerField(blank=True, null=True)
    comp6_inv = models.IntegerField(blank=True, null=True)
    comp6_rate_percent_diff = models.FloatField(blank=True, null=True)
    comp7_rate = models.IntegerField(blank=True, null=True)
    comp7_inv = models.IntegerField(blank=True, null=True)
    comp7_rate_percent_diff = models.FloatField(blank=True, null=True)
    comp8_rate = models.IntegerField(blank=True, null=True)
    comp8_inv = models.IntegerField(blank=True, null=True)
    comp8_rate_percent_diff = models.FloatField(blank=True, null=True)
    click_bool = models.BooleanField()
    gross_bookings_usd = models.FloatField(blank=True, null=True)
    booking_bool = models.BooleanField()
